# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '粗糙度软件.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(806, 610)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 20, 481, 531))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.graphicsView = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView.setGeometry(QtCore.QRect(20, 10, 431, 431))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(520, 41, 231, 441))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(610, 20, 54, 12))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(600, 500, 75, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 806, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        self.menu_6 = QtWidgets.QMenu(self.menubar)
        self.menu_6.setObjectName("menu_6")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionJie = QtWidgets.QAction(MainWindow)
        self.actionJie.setObjectName("actionJie")
        self.actionTiqu = QtWidgets.QAction(MainWindow)
        self.actionTiqu.setObjectName("actionTiqu")
        self.actionLv = QtWidgets.QAction(MainWindow)
        self.actionLv.setObjectName("actionLv")
        self.actionCAI = QtWidgets.QAction(MainWindow)
        self.actionCAI.setObjectName("actionCAI")
        self.actionPIN = QtWidgets.QAction(MainWindow)
        self.actionPIN.setObjectName("actionPIN")
        self.actionYonghuzhinan = QtWidgets.QAction(MainWindow)
        self.actionYonghuzhinan.setObjectName("actionYonghuzhinan")
        self.actionGuanyuruanjian = QtWidgets.QAction(MainWindow)
        self.actionGuanyuruanjian.setObjectName("actionGuanyuruanjian")
        self.actionTuichu = QtWidgets.QAction(MainWindow)
        self.actionTuichu.setObjectName("actionTuichu")
        self.menu.addAction(self.actionOpen)
        self.menu.addAction(self.actionSave)
        self.menu.addAction(self.actionTuichu)
        self.menu_2.addAction(self.actionJie)
        self.menu_2.addAction(self.actionTiqu)
        self.menu_2.addAction(self.actionLv)
        self.menu_3.addAction(self.actionCAI)
        self.menu_3.addAction(self.actionPIN)
        self.menu_6.addAction(self.actionYonghuzhinan)
        self.menu_6.addAction(self.actionGuanyuruanjian)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())
        self.menubar.addAction(self.menu_6.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "测量分析软件"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "显示图像"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "滤波"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "材料比分析"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "频域分析"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "粗糙度参数"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "台阶高度参数"))
        self.label.setText(_translate("MainWindow", "历史记录"))
        self.pushButton.setText(_translate("MainWindow", "清除"))
        self.menu.setTitle(_translate("MainWindow", "文件（&F）"))
        self.menu_2.setTitle(_translate("MainWindow", "预处理(&O)"))
        self.menu_3.setTitle(_translate("MainWindow", "分析(&A)"))
        self.menu_4.setTitle(_translate("MainWindow", "二维参数(&B)"))
        self.menu_5.setTitle(_translate("MainWindow", "三维参数(&C)"))
        self.menu_6.setTitle(_translate("MainWindow", "帮助(&H)"))
        self.actionOpen.setText(_translate("MainWindow", "打开"))
        self.actionSave.setText(_translate("MainWindow", "保存"))
        self.actionJie.setText(_translate("MainWindow", "截取区域"))
        self.actionTiqu.setText(_translate("MainWindow", "提取轮廓"))
        self.actionLv.setText(_translate("MainWindow", "滤波"))
        self.actionCAI.setText(_translate("MainWindow", "材料比分析"))
        self.actionPIN.setText(_translate("MainWindow", "频域分析"))
        self.actionYonghuzhinan.setText(_translate("MainWindow", "用户指南"))
        self.actionGuanyuruanjian.setText(_translate("MainWindow", "关于软件"))
        self.actionTuichu.setText(_translate("MainWindow", "退出"))

def main():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    gui = Ui_MainWindow()
    gui.setupUi(MainWindow)
    MainWindow.show()
    app.exec_()


if __name__ == '__main__':

    main()